@startuml


class ZKDatabase

class DataTree

interface NodeHashMap

class FileTxnSnapLog

class NodeHashMapImpl

ZKDatabase "1" *-down-  "1" FileTxnSnapLog
ZKDatabase "1" *-right-  "1" DataTree

DataTree "1" *-right- "1" NodeHashMap
NodeHashMapImpl -up-|> NodeHashMap

@enduml